### ISSUE TITLE
fail to install react-native-mmkv-storage

### ISSUE THREAD

**Issue by pruge** [WrathChaos/react-native-typescript-boilerplate#5]
I got the following error message:
```
no toolchains found in the ndk toolchains folder for abi with prefix: arm-linux-androideabi
```

I solved this problem like this:

> change NDK from 23.1.xxxx to 20.1.5948944

**Comment by kuraydev** [comment]
Hello @pruge,

Thank you so much for reporting this. I should add this on README as well. MMKV does not work with more than 20.x versions on NDK and CMake :(

**Comment by pruge** [comment]
I appreciate the disclosure of good boilerplate.

Here are some suggestions.
1. remove local.properties from .gitignore.
2. change AnimatedSplash.imageBackgroundSource to logoImage

It looks like [react-native-animated-splash-screen](https://www.npmjs.com/package/react-native-animated-splash-screen#props) doesn't have an imageBackgroundSource attribute.

**Comment by kuraydev** [comment]
Hi @pruge,
Actually, I'm going to remove the react-native-animated-splash-screen as a dependency. Instead, I will add a native splash screen library. This one is too objective.

About the local.properties, I could not remove it from .gitignore because it is a local environmental issue. Every dev should handle it on their own. 

Thank you for the suggestions tho :) 

Do you have any more? I would like to discuss and improve the boilerplate.

**Comment by kuraydev** [comment]
Hello @pruge 
I improved the boilerplate with version 3 :) 

Can you please check it out when you have time? 
I would like to discuss how to improve it more and more :)
